### ------------------PARTNER 1---------------------
### ------------------EVENT---------------------

### All Events GET
GET http://localhost:3000/events

### Event POST
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "New Event 2",
    "date": "2024-06-20T00:00:00",
    "description": "This is a new event",
    "price": 222
}

> {%

    client.global.set("eventId", response.body.id)
%}

### Unique Events GET
GET http://localhost:3000/events/{{eventId}}

### Event PATCH
PATCH http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
  "name": "New Event UPDATE1",
  "description": "teste"
}



### Events DELETE
DELETE http://localhost:3000/events/{{eventId}}

### ------------------SPOT---------------------

### All Spot GET
GET http://localhost:3000/events/{{eventId}}/spots

### Spot POST
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
  "name": "A3"
}

> {%

    client.global.set("spotId", response.body.id)
    client.global.set("spotName", response.body.name)
%}

### Unique Spot GET
GET http://localhost:3000/events/{{eventId}}/spots/{{spotId}}

### Spot PATCH
PATCH http://localhost:3000/events/{{eventId}}/spots/{{spotId}}
Content-Type: application/json

{
  "name": "New Spot UPDATE"
}

### Spot DELETE
DELETE http://localhost:3000/events/{{eventId}}/spots/{{spotId}}

### Reserve POST
POST http://localhost:3000/events/{{eventId}}/reserve
Content-Type: application/json

{
  "spots": ["{{spotName}}"],
  "ticket_kind": "full",
  "email": "teste@teste.com"
}

###

### ------------------PARTNER 2---------------------
### ------------------EVENT---------------------

### All Events GET
GET http://localhost:3001/eventos

### Event POST
POST http://localhost:3001/eventos
Content-Type: application/json

{
  "name": "New Event 2",
  "date": "2024-06-20T00:00:00",
  "description": "This is a new event",
  "price": 222
}

> {%

    client.global.set("eventId", response.body.id)
%}

### Unique Events GET
GET http://localhost:3001/eventos/{{eventId}}

### Event PATCH
PATCH http://localhost:3001/eventos/{{eventId}}
Content-Type: application/json

{
  "name": "New Event UPDATE1",
  "description": "teste"
}



### Events DELETE
DELETE http://localhost:3001/eventos/{{eventId}}

### ------------------SPOT---------------------

### All Spot GET
GET http://localhost:3001/eventos/{{eventId}}/assentos

### Spot POST
POST http://localhost:3001/eventos/{{eventId}}/assentos
Content-Type: application/json

{
  "name": "A3"
}

> {%

    client.global.set("spotId", response.body.id)
    client.global.set("spotName", response.body.name)
%}

### Unique Spot GET
GET http://localhost:3001/eventos/{{eventId}}/assento/{{spotId}}

### Spot PATCH
PATCH http://localhost:3001/eventos/{{eventId}}/assento/{{spotId}}
Content-Type: application/json

{
  "name": "New Spot UPDATE"
}

### Spot DELETE
DELETE http://localhost:3001/eventos/{{eventId}}/assento/{{spotId}}

### Reserve POST
POST http://localhost:3001/eventos/{{eventId}}/reserve
Content-Type: application/json

{
  "spots": ["{{spotName}}"],
  "ticket_kind": "full",
  "email": "teste@teste.com"
}

###